### PR TITLE
Allow msys2 (Depends on #6)

### PR DESCRIPTION
**Pull request by Kreijstal**
Since we update llvm depency to 18 we don't have to build llvm ourselves but we can just the version packaged by msys2.

Essentially allows compiling openvaf using the msys2 toolchain, removing the requirement of msvc.
under the ucrt enviroment simply install:
`pacboy -S --needed rust:p clang:p llvm:p cc:p`
Then `cargo build`

### CODE REVIEW

**Comment by Lang0722** [comment]
Great work! However, installing Rust in MSYS2 this way can cause rust-analyzer to lose the path to the standard library. I solved this by manually copying the library from my local Windows installation.

**Comment by Kreijstal** [comment]
> Great work! However, installing Rust in MSYS2 this way can cause rust-analyzer to lose the path to the standard library. I solved this by manually copying the library from my local Windows installation.

If you use vscode there are problems of vscode and msys2... This would get solved if we could compile chromium on msys2, fortunately, chromium is too fixed on msvc to care

**Comment by Lang0722** [comment]
> > Great work! However, installing Rust in MSYS2 this way can cause rust-analyzer to lose the path to the standard library. I solved this by manually copying the library from my local Windows installation.
> 
> If you use vscode there are problems of vscode and msys2... This would get solved if we could compile chromium on msys2, unfortunately, chromium is too fixed on msvc to care
> 
> Besides, I also think they use ancient nodejs dependencies

I mean for Rust. After configuring the default terminal window to use MSYS2's Bash, my rust-analyzer couldn't find the source code for the standard library. After further Googling and debugging, I discovered that Pacboy seems forgot to copy the standard library's source code. Simply copying the standard library's source code from Rust's Windows complete rustup installation would solve this problem. The compile of openvaf works perfectly fine.

**Comment by Kreijstal** [comment]
> > > Great work! However, installing Rust in MSYS2 this way can cause rust-analyzer to lose the path to the standard library. I solved this by manually copying the library from my local Windows installation.
> > 
> > 
> > If you use vscode there are problems of vscode and msys2... This would get solved if we could compile chromium on msys2, unfortunately, chromium is too fixed on msvc to care
> > Besides, I also think they use ancient nodejs dependencies
> 
> I mean for Rust. After configuring the default terminal window to use MSYS2's Bash, my rust-analyzer couldn't find the source code for the standard library. After further Googling and debugging, I discovered that Pacboy seems forgot to copy the standard library's source code. Simply copying the standard library's source code from Rust's Windows complete rustup installation would solve this problem. The compile of openvaf works perfectly fine.

I think that can cause issues, I believe the rust is not ABI compatible the one from rustup than the one from msys2, anyhow if you use rustup make sure you use windows-gnu and not windows-msvc targets.

**Comment by Kreijstal** [comment]
This broke because msys2 ships with llvm19 and not llvm18

**Comment by Kreijstal** [comment]
closing in favor of ci

**Pull request closed without merging**
