### PR TITLE
Adding LLVM18

### PR DESCRIPTION
**Pull request by Kreijstal**
This is an attempt

### CODE REVIEW

**Comment by arpadbuermen** [comment]
I merged it into branches/osdi_0.3_llvm18 (this is the OSDI 0.3 branch that has bugfixes, but to new features). I guess we need to make the LLVM18 version clean wrt. Pascal's tests. 
When I have time to build LLVM18 and compile openvaf I will look at it myself. In the meantime maybe Dietmar will give it a test drive.

**Comment by arpadbuermen** [comment]
I merged it into branches/osdi_0.3_llvm18 (this is the OSDI 0.3 branch that has bugfixes, but no new features). I guess we need to make the LLVM18 version clean wrt. Pascal's tests before we merge it into branches/osdi_0.3 and then later into master.
When I have time to build LLVM18 and compile openvaf I will look at it myself. In the meantime maybe Dietmar will give it a test drive.

**Comment by arpadbuermen** [comment]
Can you give me a list of files you changed using LLM. I don't trust artificial intelligence. In my opinion it should be called artificial stupidity.

**Comment by Kreijstal** [comment]
if it comes that far then forget it, what I did is simply try to remove llvm dependency, use sed to mass replace all llvm imports, with llvm_sys + some renames, and manually fix the upmost compiler error, until it compiled, which is why you see unsafe there. Is there something that is/seems nonsensical? let me know.

**Pull request closed without merging**
